---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dristiti/dristitimes-app
    - /bin/rm -rf "$DEPLOYPATH/.next" "$DEPLOYPATH/node_modules"
    - /bin/cp -R .next "$DEPLOYPATH/"
    - /bin/cp -R node_modules "$DEPLOYPATH/"
    - /bin/cp -R public "$DEPLOYPATH/"
    - /bin/cp -f server.js "$DEPLOYPATH/"
    - /bin/cp -f package.json "$DEPLOYPATH/"
    - /bin/mkdir -p "$DEPLOYPATH/tmp"
    - /bin/touch "$DEPLOYPATH/tmp/restart.txt"
